config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  devise_for :usuarios
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources 'expedientes'
  resources 'fichas'

  root to: "home#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/consultor.rb
class Consultor < ApplicationRecord
  belongs_to :usuario
  belongs_to :empresa

  # --------------- VALIDACIONES DE LOS CAMPOS --------------------------------------------
  validates :usuario_id, :empresa_id, :nombre, :apellidos,  
    presence: true

end

app/models/empresa.rb
class Empresa < ApplicationRecord
  has_many :consultors
  has_many :expedientes

  # --------------- VALIDACIONES DE LOS CAMPOS --------------------------------------------
  validates :nombre, :nif, 
    presence: true

end

app/models/expediente.rb
class Expediente < ApplicationRecord
  has_many :fichas
  belongs_to :empresa

  mount_uploader :archivo, ArchivoExpedienteUploader

  # --------------- VALIDACIONES DE LOS CAMPOS --------------------------------------------
  validates :empresa_id, :referencia,
    presence: true
  
  validates :codigo,
    uniqueness: true,
    presence: true

end

app/models/ficha.rb
class Ficha < ApplicationRecord
  belongs_to :expediente

  mount_uploader :archivo, ArchivoFichaUploader

  # --------------- VALIDACIONES DE LOS CAMPOS --------------------------------------------
  validates :expediente_id, :fecha_inicio, :referencia,  
    presence: true

  validates :descripcion, length: { maximum: 500 }

  validate :fecha_anterior_a_hoy

  def fecha_anterior_a_hoy
    if fecha_inicio > Date.today
      errors.add(:fecha_inicio, "La fecha de inicio no puede ser posterior a la fecha actual.")
    end
  end
    
end

app/models/usuario.rb
class Usuario < ApplicationRecord
  has_one :consultor

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :rememberable #, :registerable,
         # :recoverable, :rememberable, :validatable

  # --------------- VALIDACIONES DE LOS CAMPOS --------------------------------------------
  validates :email, 
    uniqueness: true,
    presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   before_action :authenticate_usuario!
end

app/controllers/expedientes_controller.rb
class ExpedientesController < ApplicationController
  #---------------------------
  def index
    @titulo   = "Expedientes"
    empresa = Usuario.where("id = #{current_usuario.id}").first.consultor.empresa
    @subtitulo      = "Listado de expedientes de la empresa '#{empresa.nombre}'"
    @expedientes = empresa.expedientes;
  end

  #---------------------------
  def show
    begin
      @registro = Expediente.find(params[:id])
      @titulo   = "Detalle de expediente " + @registro.codigo
      @subtitulo = "Empresa '#{@registro.empresa.nombre}'"
      @registroFicha = Ficha.new

    rescue => e
      flash[:error] = 'Error al intentar mostrar el registro. Intente de nuevo o comuniquese con el Proveedor del servicio.'
      redirect_to empresas_path
    end
  end

  #---------------------------
  def new
    begin
      empresa = Usuario.where("id = #{current_usuario.id}").first.consultor.empresa
      @titulo   = "Expedientes"
      @subtitulo = "Crear expediente de la empresa '#{empresa.nombre}'"

      @registro = Expediente.new

      
    rescue => e
      flash[:error] = 'Error al intentar mostrar la pantalla.'
      redirect_to empresas_path
    else
      render 'new_edit'
    end
  end

  #----------------------------------------------------------------------------------------------
  def create
    begin
      empresa = Usuario.where("id = #{current_usuario.id}").first.consultor.empresa
      @registro = Expediente.new(lista_params)
      @registro.empresa_id = empresa.id

      # busqueda y creacion del nuevo codigo a partir del ultimo creado
      ultimoExpediente = Expediente.last
      autonumerico = ultimoExpediente.nil? ? 0 : ultimoExpediente.codigo[3..7].to_i
      autonumerico += 1 
      anioActual = Date.today.strftime("%y")
      autonumericoTxt = anioActual.to_s + '-' + autonumerico.to_s.rjust(4, '0')
      @registro.codigo = autonumericoTxt

      if @registro.valid?
        unless @registro.save
          raise 'No se pudo guardar'
        end
      else
        raise 'Campos con errores'
      end

    rescue => e
      @titulo   = "Expedientes"
      @subtitulo = "Crear expediente de la empresa '#{empresa.nombre}'"
      flash[:error] = 'Error al intentar registrar los cambios en la Base de Datos.'
      render 'new_edit'
    else
      flash[:success] = 'Nuevo registro creado correctamente.'
      redirect_to @registro
    end
  end

  #---------------------------
  def edit
    begin
      @registro = Expediente.find(params[:id])
      @titulo   = "Editar expediente " + @registro.codigo
      @subtitulo = "Empresa '#{@registro.empresa.nombre}'"
      
    rescue => e
      flash[:error] = 'Error al intentar mostrar la pantalla.'
      redirect_to empresas_path
    else
      render 'new_edit'
    end
  end

  #-----------------------------------------------------------------
  def update
    begin
      @registro = Expediente.find(params[:id])
      @registro.update(lista_params)

    rescue => e
      empresa = Usuario.where("id = #{current_usuario.id}").first.consultor.empresa
      @titulo   = "Expedientes"
      @subtitulo = "Editar expediente de la empresa '#{empresa.nombre}'"
      flash[:error] = 'Error al intentar registrar los cambios en la Base de Datos.'
      render 'new_edit'

    else
      flash[:success] = 'Los cambios se registraron correctamente.'
      redirect_to expediente_path(@registro.id)
    end
  end


 #------------------------------------------------------------------
 def destroy
  begin
    registro = Expediente.find(params[:id])
    registro.destroy
  rescue => e
    flash[:error] = 'Error al intentar borrar el registro.'
    redirect_to action: :show, id: param_id
  else
    flash[:success] = 'El registro se eliminó correctamente.'
    redirect_to action: :index
  end
end

#------------------------------------------------------------------
#------------------------------------------------------------------
private

  #------------------------------------------------------------------
  def lista_params
    params.require(:expediente).permit(:referencia, :descripcion, :archivo)
  end

end

app/controllers/fichas_controller.rb
class FichasController < ApplicationController
  #----------------------------------------------------------------------------------------------
  def create
    begin
      @registroFicha = Ficha.new(lista_params)
      @registro = Expediente.find(@registroFicha.expediente_id)
      @titulo   = "Detalle de expediente " + @registro.codigo
      @subtitulo = "Empresa '#{@registro.empresa.nombre}'"
      
      if @registroFicha.valid?
        unless @registroFicha.save
          raise 'No se pudo guardar'
        else
          @registroFicha = Ficha.new
        end
      else
        raise 'Campos con errores'
      end
      
    rescue => e
      flash[:error] = 'Error al intentar guardar el registro.'
      render 'expedientes/show'
    else
      flash[:success] = 'Nuevo registro creado correctamente.'
      redirect_to expediente_path(@registro.id)
    end
  end

  #------------------------------------------------------------------
  #------------------------------------------------------------------
  private

  #------------------------------------------------------------------
  def lista_params
    params.require(:ficha).permit(:expediente_id, :fecha_inicio, :referencia, :descripcion, :archivo)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/expedientes_helper.rb
module ExpedientesHelper
end

app/helpers/fichas_helper.rb
module FichasHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/expedientes/index.html.erb
<%= render 'layouts/titulo' %>

<div class="row text-end mb-3">
    <div class="col">
      <%= link_to "Crear expediente", new_expediente_path, class:"btn btn-primary" %>
    </div>
</div>

<div class="row">
  <div class="col mx-3 px-3 py-3 bg-light">

    <table id="myDataTable" class="table table-striped table-hover table-bordered">
      <thead>
        <tr>
          <td>Código</td>
          <td>Referencia</td>
          <td>Cantidad de fichas</td>
          <td>Acciones</td>
        </tr>
      </thead>

      <tbody>
        <% @expedientes.each do |r| %>
          <tr>
            <td>
              <%= r.codigo%>
            </td>
            <td>
              <%= truncate(r.referencia, :length => 30) %>
            </td>
            <td>
              <%= r.fichas.count%>
            </td>
            <td>
              <%= link_to "Ver", expediente_path(r.id), class:"btn btn-success btn-sm mx-2" %>
              <%= link_to "Editar", edit_expediente_path(r.id), class:"btn btn-secondary btn-sm mx-2" %>
              <%= link_to "Eliminar", 
                expediente_path(r.id), 
                data: {confirm: '¿Está seguro de eliminar este registro?'}, 
                method: :delete, 
                class:"btn btn-danger btn-sm mx-2" 
              %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    
  </div>
</div>

app/views/expedientes/new_edit.html.erb
<%= render 'layouts/titulo' %>

<div class="row">
  <div class="col">
    <h6 class="my-4">
      <% if @registro.new_record? %>
        Suministre los datos requeridos.
      <% else %>
        Modifique los datos que necesite.
      <% end %>
    </h6>

    <%= form_with(model: @registro, local: true) do |f| %>
      <div class="form-group text-start my-3">
        <label for="referencia" class="form-label fw-bold">Referencia:</label>
        <%= f.text_field :referencia, class: "form-control", required: true %>
        <span class="form-text text-danger">
          <%= @registro.errors[:referencia].any? ? @registro.errors[:referencia].to_s[/\w([^"]*)/] : "" %>
        </span>
      </div>

      <div class="form-group text-start my-3">
        <label for="descripcion" class="form-label fw-bold">Descripción:</label>
        <%= f.text_field :descripcion, class: "form-control" %>
        <span class="form-text text-danger">
          <%= @registro.errors[:descripcion].any? ? @registro.errors[:descripcion].to_s[/\w([^"]*)/] : "" %>
        </span>
      </div>

      <div class="form-group text-start my-3">
        <label for="archivo" class="form-label fw-bold">Archivo:</label>
        <%= f.file_field :archivo, class: "form-control" %>
        <span class="form-text text-danger">
          <%= @registro.errors[:archivo].any? ? @registro.errors[:archivo].to_s[/\w([^"]*)/] : "" %>
        </span>
      </div>

      <div class="text-center my-5">
        <%= link_to "Regresar al Listado", expedientes_path, class: "btn btn-default btn-md" %>
        <%= f.submit "Guardar", class: 'btn btn-primary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/expedientes/show.html.erb
<%= render 'layouts/titulo' %>

<div class="row mb-3">
    <div class="col">
      <%= label_tag :codigo, 'Referencia:', class: '' %>
      <%= text_field_tag :codigo, @registro.referencia, disabled: true %>
    </div>

    <div class="col">
      <%= label_tag :codigo, 'Descripción:', class: '' %>
      <%= text_field_tag :codigo, @registro.descripcion, disabled: true %>
    </div>

    <div class="col">
      <%= label_tag :codigo, 'Archivo:', class: '' %>
      <br/>
      <%= link_to "Descargar", @registro.archivo.url, class:"btn btn-outline-info btn-sm mx-2", target: '_blank' %>

    </div>
</div>

<div class="row">
    <div class="col my-3">
      <%= link_to "Listar", expedientes_path, class:"btn btn-success btn-sm mx-2" %>
      <%= link_to "Crear", new_expediente_path, class:"btn btn-primary btn-sm mx-2" %>
      <%= link_to "Editar", edit_expediente_path(@registro.id), class:"btn btn-secondary btn-sm mx-2" %>
      <%= link_to "Eliminar", 
        expediente_path(@registro.id), 
        data: {confirm: '¿Está seguro de eliminar este registro?'}, 
        method: :delete, 
        class:"btn btn-danger btn-sm mx-2" 
      %>
    </div>
</div>

<hr/>

<div class="row">
  <div class="col mx-3 px-3 py-3 bg-light">
    <h3>FICHAS</h3>

    <%= render 'fichas/new' %>
    <%= render 'fichas/index' %>
  </div>
</div>

app/views/fichas/_index.html.erb
<table id="myDataTable" class="table table-striped table-hover table-bordered">
  <thead>
    <tr>
      <td>Fecha inicio</td>
      <td>Referencia</td>
      <td>Descripción</td>
      <td>Archivo</td>
      <td>Acciones</td>
    </tr>
  </thead>

  <tbody>
    <% @registro.fichas.each do |r| %>
      <tr>
        <td>
          <%= r.fecha_inicio.to_formatted_s(:dia_mes_ano) %>
        </td>
        <td>
          <%= truncate(r.referencia, :length => 30) %>
        </td>
        <td>
          <%= r.descripcion %>
        </td>
        <td>
          <%= link_to "Descargar", r.archivo.url, class:"btn btn-outline-info btn-sm mx-2", target: '_blank' %>
        </td>
        <td>
          <%= link_to "Eliminar", 
            ficha_path(r.id), 
            data: {confirm: '¿Está seguro de eliminar este registro?'}, 
            method: :delete, 
            class:"btn btn-danger btn-sm mx-2" 
          %>
        </td>
      </tr>
    <% end %>
  </tbody> 
</table>

app/views/fichas/_new.html.erb
<%= form_with(model: @registroFicha, local: true) do |f| %>
  <div class="row text-start mt-4 pb-2">
    <div class="col">
        <%= f.hidden_field :expediente_id, :value => @registro.id %>
        <label for="fecha_inicio" class="form-label fw-bold">Fecha inicio:</label>
        <%= f.text_field :fecha_inicio, class: "form-control datetimepicker-input", required: true, "data-target": "#ficha_fecha_inicio", "data-toggle": "datetimepicker" %>
        <span class="form-text text-danger">
          <%= @registroFicha.errors[:fecha_inicio].any? ? @registroFicha.errors[:fecha_inicio].to_s[/\w([^"]*)/] : "" %>
        </span>
    </div>

    <div class="col">
        <label for="referencia" class="form-label fw-bold">Referencia:</label>
        <%= f.text_field :referencia, class: "form-control", required: true %>
        <span class="form-text text-danger">
          <%= @registroFicha.errors[:referencia].any? ? @registroFicha.errors[:referencia].to_s[/\w([^"]*)/] : "" %>
        </span>
    </div>
  </div>

  <div class="row text-start">
    <div class="col">
        <label for="descripcion" class="form-label fw-bold">Descripción:</label>
        <%= f.text_field :descripcion, class: "form-control" %>
        <span class="form-text text-danger">
          <%= @registroFicha.errors[:descripcion].any? ? @registroFicha.errors[:descripcion].to_s[/\w([^"]*)/] : "" %>
        </span>
    </div>

    <div class="col">
        <label for="archivo" class="form-label fw-bold">Archivo:</label>
        <%= f.file_field :archivo, class: "form-control" %>
        <span class="form-text text-danger">
          <%= @registroFicha.errors[:archivo].any? ? @registroFicha.errors[:archivo].to_s[/\w([^"]*)/] : "" %>
        </span>
    </div>
  </div>
  
  <div class="row text-center my-4 pb-3">
    <div class="col">
      <%= f.submit "Agregar ficha", class: 'btn btn-primary btn-sm' %>
    </div>
  </div>
<% end %>

app/views/home/index.html.erb
<br/><br/><br/><br/><br/>
<h1>Aplicación de pruebas UBT L&C</h1>
<p>Consulta y modificacion de expedientes y fichas</p>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">UBT L&C</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to 'Expedientes', expedientes_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Salir', destroy_usuario_session_path, method: :delete, class:"nav-link" %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_titulo.html.erb
<h1 class="text-start">
  <%= @titulo %>
</h1>
<p class="text-start">
  <%= @subtitulo %>
</p>

<hr/>

<div class="py-2"></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PruebaUBT</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-fluid vh-100">
      <% if usuario_signed_in? %>
        <%= render 'layouts/header' %>
      <% end %>

      <div class="row text-center h-90">
          <div class="col mt-2">
            <% if notice %>
              <p class="notice"><%= notice %></p>
            <% end %>

            <% if alert %>
              <p class="alert"><%= alert %></p>
            <% end %>

            <%= yield %>
          </div>
      </div>

    </div>
  </body>
</html>